apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: g7qe7nc3v-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: g7qe7nc3v-nodejs 
  name: g7qe7nc3v-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: g7qe7nc3v-nodejs 
